name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_push_to_DockerHub:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag muyangren907/ros:melodic
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: muyangren907/ros
        tags: melodic
  build_and_push_to_Aliyun_HK:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag muyangren907/ros:melodic
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Aliyun HK
      uses: docker/build-push-action@v1
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: registry.cn-hongkong.aliyuncs.com/muyangren907/ros-hk
        tags: melodic
